# Generated by Django 4.1 on 2022-10-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0002_issue_issue_date_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
