# Generated by Django 4.1 on 2022-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='user_id_gen()', max_length=10, primary_key=True, serialize=False),
        ),
    ]
