# Generated by Django 4.1 on 2022-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
