# Generated by Django 4.1 on 2022-10-22 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0005_user_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.TextField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(default='Untitled', max_length=60)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('data_created', models.DateField(default=django.utils.timezone.now)),
                ('book_type', models.IntegerField(default=1)),
                ('thumbnail', models.ImageField(upload_to='book/<django.db.models.fields.TextField>')),
                ('pdf_files', models.FileField(upload_to='book/<django.db.models.fields.TextField>/pdfs')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.book')),
                ('writer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=3.0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.book')),
                ('reviewer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('msg', models.CharField(blank=True, max_length=100)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.book')),
                ('reporter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('msg', models.CharField(max_length=500)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.book')),
                ('issuer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(blank=True, to='database_models.book')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.book')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
