# Generated by Django 4.1 on 2022-10-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0006_book_alter_user_user_id_writes_reviews_reports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
