# Generated by Django 4.1 on 2022-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0006_book_alter_user_user_id_writes_reviews_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='bio'),
        ),
    ]
